kind: Deployment
metadata:
  name: shopping-list-deployment
  annotations:
    version: 0.0.1-SNAPSHOT
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: shopping-list
        component: shopping-list
    spec:
      containers:
        - name: shopping-list
          image: shopping-list:0.0.1-SNAPSHOT
            ports:
            - containerPort: 8080
            - containerPort: 8443
          lifecycle:
            preStop:
              exec:
                # SIGTERM triggers a quick exit; gracefully terminate instead
                command: ["kill", "-SIGINT", "`pidof java`"]
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/ready
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{spring_profile}}
          resources:
            requests:
              cpu: {{cpu_request or '500m'}}
              memory: {{memory_request or '1Gi'}}
            limits:
              cpu: {{cpu_limit or '1000m'}}
              memory: {{memory_limit or '2.5Gi'}}
---
kind: Service
apiVersion: v1
metadata:
  name: shopping-list-service
spec:
  type: Loadbalancer
  selector:
    name: shopping-list
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    component: shopping-list
  name: shopping-list
spec:
  to:
    kind: Service
    name: shopping-list
  tls:
    termination: passthrough
